### ISSUE TITLE
./configure fails with "cannot find input file: `Makefile.in'"

### ISSUE THREAD

**Issue by SpiritQuaddicted** [ahefner/sdlquake#2]
Probably just a documentation issue but I saw the pull request and decided to build. Docs say "./configure && make" which gave me the following error:

```
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
```

I am on Archlinux if that matters.

**Comment by ahefner** [comment]
Thanks for pointing that out. I've removed the rest of the autotools-generated files (such as the configure script itself) and added an autogen.sh script to regenerate them. Having some but not all of them lingering in the repository was confusing. Updated documentation.

That said, there's some crash issue, at least when I build it on my machine, so it's probably not usable in its present state, barring whatever configuration MightyJo builds it under.
